{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "statistics-for-strava.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host }}
      http:
        paths:
          - path: {{ (index .Values.ingress.hosts 0).path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "statistics-for-strava.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}