apiVersion: v1
kind: Secret
metadata:
  name: {{ include "statistics-for-strava.fullname" . }}-env
type: Opaque
stringData:
  {{- range $k, $v := .Values.secretEnv }}
  {{ $k }}: "{{ $v }}"
  {{- end }}